#ifndef _GLWRAP_
#define _GLWRAP_
#include <glwrap/FileManager.h>
#include <glwrap/Context.h>
#include <glwrap/VertexBuffer.h>
#include <glwrap/VertexArray.h>
#include <glwrap/ObjPart.h>
#include <glwrap/ObjMtlModel.h>
#include <glwrap/Material.h>
#include <glwrap/ObjAnimation.h>
#include <glwrap/ObjFrame.h>
#include <glwrap/ShaderProgram.h>
#include <glwrap/Texture.h>
#include <glwrap/RenderTexture.h>
#include <glwrap/GBuffer.h>
#include <glwrap/DepthBuffer.h>
#include <glwrap/DepthCube.h>
#include <glwrap/ViewingFrustum.h>
#endif